# Generated by Django 3.2.8 on 2021-10-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fio',
            old_name='Name',
            new_name='filter',
        ),
    ]
