# Generated by Django 3.2.8 on 2021-10-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_fio_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('Description', models.TextField(verbose_name='Описание')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('mass', models.IntegerField(verbose_name='Масса')),
                ('imagefile', models.ImageField(upload_to='main/static/main/loadimg')),
            ],
        ),
    ]
