# Generated by Django 3.2.8 on 2021-10-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_title_tovars_title_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tovars',
            new_name='Tovar',
        ),
    ]
