# Generated by Django 3.2.8 on 2021-10-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_tovars_tovar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tovar',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
