# Generated by Django 3.2.8 on 2021-10-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tovar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='mass',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Масса'),
        ),
    ]
