# Generated by Django 3.2.8 on 2021-10-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211027_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='mass',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Масса'),
        ),
    ]
